import type {NextPage} from "next";
import Head from "next/head";
import {trpc} from "../../utils/trpc";
import {useRouter} from "next/router";
import Image from "next/image";

const GithubUser: NextPage = () => {
  const {query} = useRouter()
  const {data} = trpc.useQuery(["github.getUser", {username: query.user as string}]);
  return data ? (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {data.login}
        <Image height={64} width={64} src={data.avatar_url}/>
      </main>
    </>
  ) : null
};

export default GithubUser;
